# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MyServiceStub(object):
    """Definisikan layanan yang menggunakan 4 jenis metode
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UnaryMethod = channel.unary_unary(
                '/myservice.MyService/UnaryMethod',
                request_serializer=service__pb2.RequestMessage.SerializeToString,
                response_deserializer=service__pb2.ResponseMessage.FromString,
                _registered_method=True)
        self.ServerStreamingMethod = channel.unary_stream(
                '/myservice.MyService/ServerStreamingMethod',
                request_serializer=service__pb2.RequestMessage.SerializeToString,
                response_deserializer=service__pb2.ResponseMessage.FromString,
                _registered_method=True)
        self.ClientStreamingMethod = channel.stream_unary(
                '/myservice.MyService/ClientStreamingMethod',
                request_serializer=service__pb2.RequestMessage.SerializeToString,
                response_deserializer=service__pb2.ResponseMessage.FromString,
                _registered_method=True)
        self.BidirectionalStreamingMethod = channel.stream_stream(
                '/myservice.MyService/BidirectionalStreamingMethod',
                request_serializer=service__pb2.RequestMessage.SerializeToString,
                response_deserializer=service__pb2.ResponseMessage.FromString,
                _registered_method=True)


class MyServiceServicer(object):
    """Definisikan layanan yang menggunakan 4 jenis metode
    """

    def UnaryMethod(self, request, context):
        """Unary method
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerStreamingMethod(self, request, context):
        """Server streaming method
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientStreamingMethod(self, request_iterator, context):
        """Client streaming method
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BidirectionalStreamingMethod(self, request_iterator, context):
        """Bidirectional streaming method
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UnaryMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.UnaryMethod,
                    request_deserializer=service__pb2.RequestMessage.FromString,
                    response_serializer=service__pb2.ResponseMessage.SerializeToString,
            ),
            'ServerStreamingMethod': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerStreamingMethod,
                    request_deserializer=service__pb2.RequestMessage.FromString,
                    response_serializer=service__pb2.ResponseMessage.SerializeToString,
            ),
            'ClientStreamingMethod': grpc.stream_unary_rpc_method_handler(
                    servicer.ClientStreamingMethod,
                    request_deserializer=service__pb2.RequestMessage.FromString,
                    response_serializer=service__pb2.ResponseMessage.SerializeToString,
            ),
            'BidirectionalStreamingMethod': grpc.stream_stream_rpc_method_handler(
                    servicer.BidirectionalStreamingMethod,
                    request_deserializer=service__pb2.RequestMessage.FromString,
                    response_serializer=service__pb2.ResponseMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myservice.MyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('myservice.MyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MyService(object):
    """Definisikan layanan yang menggunakan 4 jenis metode
    """

    @staticmethod
    def UnaryMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/myservice.MyService/UnaryMethod',
            service__pb2.RequestMessage.SerializeToString,
            service__pb2.ResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerStreamingMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/myservice.MyService/ServerStreamingMethod',
            service__pb2.RequestMessage.SerializeToString,
            service__pb2.ResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClientStreamingMethod(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/myservice.MyService/ClientStreamingMethod',
            service__pb2.RequestMessage.SerializeToString,
            service__pb2.ResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BidirectionalStreamingMethod(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/myservice.MyService/BidirectionalStreamingMethod',
            service__pb2.RequestMessage.SerializeToString,
            service__pb2.ResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
