# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\tmyservice\"-\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x9f\x02\n\tMyService\x12?\n\nUnaryHello\x12\x17.myservice.HelloRequest\x1a\x18.myservice.HelloResponse\x12H\n\x11ServerStreamHello\x12\x17.myservice.HelloRequest\x1a\x18.myservice.HelloResponse0\x01\x12H\n\x11\x43lientStreamHello\x12\x17.myservice.HelloRequest\x1a\x18.myservice.HelloResponse(\x01\x12=\n\x04\x43hat\x12\x17.myservice.HelloRequest\x1a\x18.myservice.HelloResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=28
  _globals['_HELLOREQUEST']._serialized_end=73
  _globals['_HELLORESPONSE']._serialized_start=75
  _globals['_HELLORESPONSE']._serialized_end=107
  _globals['_MYSERVICE']._serialized_start=110
  _globals['_MYSERVICE']._serialized_end=397
# @@protoc_insertion_point(module_scope)
